[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'none'; script-src https://www.privacyguides.org 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; font-src 'self' data:; img-src data: https://*.privacyguides.net 'self'; connect-src https://api.github.com https://*.privacyguides.net https://www.privacyguides.org 'self'; frame-src https://*.privacyguides.net https://snowflake.torproject.org; frame-ancestors 'none'"
    Permissions-Policy = "browsing-topics=(), conversion-measurement=(), interest-cohort=(), accelerometer=(), ambient-light-sensor=(), battery=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), usb=()"

[[redirects]]
    from = "/es/*"
    to = "/i18n/404.es.html"
    status = 404

[[redirects]]
    from = "/fr/*"
    to = "/i18n/404.fr.html"
    status = 404

[[redirects]]
    from = "/he/*"
    to = "/i18n/404.he.html"
    status = 404

[[redirects]]
    from = "/it/*"
    to = "/i18n/404.it.html"
    status = 404

[[redirects]]
    from = "/nl/*"
    to = "/i18n/404.nl.html"
    status = 404

[[redirects]]
    from = "/zh-hant/*"
    to = "/i18n/404.zh-Hant.html"
    status = 404

[[redirects]]
    from = "/ru/*"
    to = "/i18n/404.ru.html"
    status = 404

[[redirects]]
    from = "/*"
    to = "/i18n/404.en.html"
    status = 404

[[plugins]]
  package = "@netlify/plugin-lighthouse"

    [[plugins.inputs.audits]]
        path = "en"

    [[plugins.inputs.audits]]
        path = "en/tools"

    [[plugins.inputs.audits]]
        path = "en/basics/why-privacy-matters"

    [[plugins.inputs.audits]]
        path = "en/vpn"
