name: Production Deployment

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

on:
  workflow_call:
    inputs:
      netlify_production:
        type: boolean
        default: true
      github_pages:
        type: boolean
        default: true
      minio_production:
        type: boolean
        default: true
      cloudflare_pages:
        type: boolean
        default: true
      ipfs_production:
        type: boolean
        default: true
    outputs:
      netlify_preview_address:
        value: ${{ jobs.netlify.outputs.address }}
    secrets:
      NETLIFY_TOKEN:
      PROD_MINIO_KEY_ID:
      PROD_MINIO_SECRET_KEY:
      CF_API_TOKEN:
      CF_ACCOUNT_ID:
      CLUSTER_USERNAME:
      CLUSTER_PASSWORD:
      CLOUDFLARE_ZONE:
      CLOUDFLARE_TOKEN:

jobs:
  netlify:
    if: inputs.netlify_production
    uses: ./.github/workflows/deploy-netlify.yml
    with:
      environment: production
    secrets:
      NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

  minio:
    if: inputs.minio_production
    uses: ./.github/workflows/deploy-minio.yml
    with:
      environment: production
    secrets:
      PROD_MINIO_KEY_ID: ${{ secrets.PROD_MINIO_KEY_ID }}
      PROD_MINIO_SECRET_KEY: ${{ secrets.PROD_MINIO_SECRET_KEY }}

  pages:
    if: inputs.github_pages
    uses: ./.github/workflows/deploy-pages.yml
    with:
      environment: github-pages

  cloudflare:
    if: inputs.cloudflare_pages
    uses: ./.github/workflows/deploy-cloudflare.yml
    with:
      environment: cloudflare-pages
    secrets:
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  ipfs:
    if: inputs.ipfs_production
    uses: ./.github/workflows/deploy-ipfs.yml
    with:
      environment: dweb
    secrets:
      CLUSTER_USERNAME: ${{ secrets.CLUSTER_USERNAME }}
      CLUSTER_PASSWORD: ${{ secrets.CLUSTER_PASSWORD }}
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
